import { Scene, StandardMaterial, DynamicTexture, Texture, Color3, Color4, Mesh, MeshBuilder, VertexData, Vector3, TransformNode, ArcRotateCamera, DefaultRenderingPipeline, SSAO2RenderingPipeline, HemisphericLight, DirectionalLight, ShadowGenerator } from '@babylonjs/core';

// Deterministic, locally generated art: no network or placeholder asset dependency.
let seed=9173;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
function texture(scene:Scene,name:string,size:number,paint:(c:CanvasRenderingContext2D,n:number)=>void){const t=new DynamicTexture(name,{width:size,height:size},scene,true);paint(t.getContext() as unknown as CanvasRenderingContext2D,size);t.update();t.wrapU=t.wrapV=Texture.WRAP_ADDRESSMODE;t.anisotropicFilteringLevel=8;return t;}
function material(scene:Scene,name:string,color:string){const m=new StandardMaterial(name,scene);m.diffuseColor=Color3.FromHexString(color);m.specularColor=new Color3(.09,.08,.06);return m;}

export function roundedBox(scene:Scene,name:string,w:number,h:number,d:number):Mesh{
 const r=Math.min(.055,Math.min(w,h,d)*.23),half=[w/2,h/2,d/2],inner=half.map(v=>v-r),pos:number[]=[],norm:number[]=[],uv:number[]=[],idx:number[]=[];
 const steps=6;
 for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const u=(axis+1)%3,v=(axis+2)%3,offset=pos.length/3;for(let j=0;j<=steps;j++)for(let i=0;i<=steps;i++){const p=[0,0,0];p[axis]=half[axis]*sign;p[u]=(i/steps*2-1)*half[u];p[v]=(j/steps*2-1)*half[v];const q=p.map((a,k)=>Math.max(-inner[k],Math.min(inner[k],a)));const n=new Vector3(p[0]-q[0],p[1]-q[1],p[2]-q[2]).normalize();pos.push(q[0]+n.x*r,q[1]+n.y*r,q[2]+n.z*r);norm.push(n.x,n.y,n.z);uv.push(i/steps,j/steps);}for(let j=0;j<steps;j++)for(let i=0;i<steps;i++){const a=offset+j*(steps+1)+i,b=a+1,c=a+steps+1,e=c+1;if(sign>0)idx.push(a,c,b,b,c,e);else idx.push(a,b,c,b,e,c);}}
 const mesh=new Mesh(name,scene);const data=new VertexData();data.positions=pos;data.normals=norm;data.uvs=uv;data.indices=idx;data.applyToMesh(mesh);return mesh;
}

export function upgradeArt(scene:Scene,camera:ArcRotateCamera,shadow:ShadowGenerator,girl:TransformNode){
 const get=(name:string)=>scene.getMaterialByName(name) as StandardMaterial;
 const fabric=(name:string,color:string)=>texture(scene,name,512,(c,n)=>{c.fillStyle=color;c.fillRect(0,0,n,n);for(let i=0;i<n;i+=2){c.strokeStyle=i%4?'#ffffff12':'#30201618';c.lineWidth=.7;c.beginPath();c.moveTo(0,i);c.lineTo(n,i);c.stroke();c.beginPath();c.moveTo(i,0);c.lineTo(i,n);c.stroke()}for(let i=0;i<9000;i++){c.fillStyle=rand()>.5?'#ffffff16':'#2719060b';c.fillRect(rand()*n,rand()*n,1,1)}});
 for(const [name,color]of [['rose linen','#c39182'],['cotton','#ece2cf'],['dress','#739398']]){const m=get(name);m.diffuseTexture=fabric(name+' weave',color);m.diffuseColor=Color3.White();}
 for(const [name,color]of [['honey oak','#b58c61'],['light oak','#d1b38a'],['walnut','#755342']]){const t=texture(scene,name+' grain',512,(c,n)=>{c.fillStyle=color;c.fillRect(0,0,n,n);for(let i=0;i<650;i++){const y=rand()*n;c.strokeStyle=rand()>.5?'#51331813':'#fff4d021';c.lineWidth=rand()*1.5+.3;c.beginPath();c.moveTo(0,y);for(let x=0;x<=n;x+=8)c.lineTo(x,y+Math.sin(x*.017+i)*2+Math.sin(x*.04+i)*.8);c.stroke()}for(let i=0;i<5;i++){c.strokeStyle='#5b361211';for(let r=1;r<10;r++){c.beginPath();c.ellipse(80+i*87,rand()*n,15+r*3,1+r*.6,0,0,Math.PI*2);c.stroke()}}});get(name).diffuseTexture=t;get(name).diffuseColor=Color3.White();}
 // Painted wallpaper, separate from the cream lower wainscot.
 const wallpaper=texture(scene,'botanical wallpaper',512,(c,n)=>{c.fillStyle='#c3c8b4';c.fillRect(0,0,n,n);for(let i=0;i<16000;i++){c.fillStyle=rand()>.5?'#ffffff0b':'#66745608';c.fillRect(rand()*n,rand()*n,1,1)}for(let row=0;row<4;row++)for(let col=0;col<4;col++){const x=col*128+(row%2)*64,y=row*128;c.strokeStyle='#71857045';c.lineWidth=1.5;c.beginPath();c.moveTo(x,y+100);c.bezierCurveTo(x+17,y+67,x-15,y+38,x+3,y+15);c.stroke();for(let k=0;k<5;k++){c.fillStyle=k%2?'#7f937a39':'#e6dfba88';c.beginPath();c.ellipse(x+(k%2?8:-6),y+24+k*13,5,11,k%2?.6:-.6,0,7);c.fill();}c.fillStyle='#e7dec2';for(let k=0;k<5;k++){c.beginPath();c.ellipse(x+3+Math.cos(k*1.26)*5,y+12+Math.sin(k*1.26)*5,4,2,k*1.26,0,7);c.fill()}}});
 wallpaper.uScale=3;wallpaper.vScale=1.5;get('sage plaster').diffuseTexture=wallpaper;get('sage plaster').diffuseColor=Color3.White();
 const painted=material(scene,'ivory panel paint','#c9caba');
 const addBox=(name:string,x:number,y:number,z:number,w:number,h:number,d:number,m:StandardMaterial)=>{const o=roundedBox(scene,name,w,h,d);o.position.set(x,y,z);o.material=m;o.receiveShadows=true;shadow.addShadowCaster(o);return o;};
 addBox('back wainscot',0,.64,3.265,8,1.15,.045,painted);addBox('side wainscot',-3.86,.64,0,.045,1.15,6.7,painted);
 for(let x=-3.8;x<3.9;x+=.65)addBox('raised panel stile',x,.66,3.218,.045,.99,.035,get('warm ivory'));
 for(let z=-3.2;z<3.4;z+=.65)addBox('side raised panel stile',-3.81,.66,z,.035,.99,.045,get('warm ivory'));
 addBox('back dado molding',0,1.24,3.22,8,.08,.12,get('warm ivory'));addBox('side dado molding',-3.81,1.24,0,.12,.08,6.8,get('warm ivory'));
 // Muted planks with per-board tone and visible grain, replacing the heavy grid.
 scene.meshes.filter(m=>m.name==='plank seam'||m.name==='plank end').forEach(m=>m.dispose());
 for(let row=0;row<17;row++)for(let col=0;col<5;col++){const x=-4+col*1.9-(row%2)*.9,w=Math.min(4,x+1.89)-Math.max(-4,x);if(w<=0)continue;const pm=get('light oak').clone('board '+row+' '+col)!;const tone=.9+rand()*.13;pm.diffuseColor=new Color3(tone,tone*.99,tone*.97);addBox('individual floor board',Math.max(-4,x)+w/2,.048,-3.2+row*.4,w,.012,.393,pm)}
 const rug=get('rug sage');rug.diffuseColor=Color3.White();rug.diffuseTexture=texture(scene,'embroidered medallion rug',1024,(c,n)=>{c.fillStyle='#adb09a';c.fillRect(0,0,n,n);const cx=n/2;for(let r=480;r>30;r-=8){c.strokeStyle=r%24===0?'#e5ddbc66':'#606f621d';c.lineWidth=r%24===0?3:1;c.beginPath();c.arc(cx,cx,r,0,7);c.stroke()}for(let i=0;i<36;i++){const a=i*Math.PI*2/36;const x=cx+Math.cos(a)*405,y=cx+Math.sin(a)*405;c.save();c.translate(x,y);c.rotate(a);c.fillStyle='#eae0c1';c.beginPath();c.ellipse(0,0,18,7,0,0,7);c.fill();c.restore()}for(let i=0;i<12;i++){const a=i*Math.PI/6;c.save();c.translate(cx,cx);c.rotate(a);c.fillStyle='#dfd7b5aa';c.beginPath();c.ellipse(100,0,75,18,0,0,7);c.fill();c.restore()}for(let i=0;i<55000;i++){c.fillStyle=rand()>.5?'#fff9e21b':'#374a3520';c.fillRect(rand()*n,rand()*n,1.5,1)}});
 // Actual draped fabric surface, with embroidered flowers and scalloped edges.
 scene.meshes.filter(m=>m.name==='duvet'||m.name==='quilt stitching').forEach(m=>m.dispose());
 const blanketMat=material(scene,'embroidered duvet','#ffffff');blanketMat.diffuseTexture=texture(scene,'duvet embroidery',1024,(c,n)=>{c.fillStyle='#c29584';c.fillRect(0,0,n,n);for(let y=0;y<n;y+=3){c.fillStyle='#fff5df16';c.fillRect(0,y,n,1)}for(let y=80;y<n;y+=145)for(let x=75;x<n;x+=145){c.strokeStyle='#647d6966';c.lineWidth=3;c.beginPath();c.moveTo(x,y+25);c.quadraticCurveTo(x+10,y,x,y-18);c.stroke();c.fillStyle='#e8d9b6';for(let k=0;k<6;k++){c.beginPath();c.ellipse(x+Math.cos(k)*9,y-18+Math.sin(k)*9,7,4,k,0,7);c.fill()}c.fillStyle='#ab755d';c.beginPath();c.arc(x,y-18,4,0,7);c.fill();}c.strokeStyle='#efd9b7';c.lineWidth=12;c.strokeRect(25,25,n-50,n-50);});
 const paths:Vector3[][]=[];for(let j=0;j<=32;j++){const row:Vector3[]=[];for(let i=0;i<=32;i++){const u=i/32,v=j/32,x=(u-.5)*1.94,drop=Math.max(0,Math.abs(x)-.72);row.push(new Vector3(-2.72+x,.94-drop*2.6+Math.sin(u*38+v*3)*(.007+drop*.12)+Math.sin(v*23)*.012,.04+v*1.92))}paths.push(row)}
 const blanket=MeshBuilder.CreateRibbon('soft draped quilt',{pathArray:paths,sideOrientation:Mesh.DOUBLESIDE},scene);blanket.material=blanketMat;blanket.receiveShadows=true;shadow.addShadowCaster(blanket);
 // Soft cushions with piping.
 const pillow=scene.getMeshByName('pillow');if(pillow){pillow.scaling.set(1.3,.24,.64);pillow.rotation.y=.06;}
 for(const x of [-3.38,-2.06]){const post=MeshBuilder.CreateLathe('turned bedpost',{shape:[new Vector3(0,0,0),new Vector3(.07,0,0),new Vector3(.075,.1,0),new Vector3(.04,.25,0),new Vector3(.045,1.1,0),new Vector3(.08,1.2,0),new Vector3(.055,1.28,0),new Vector3(0,1.3,0)],tessellation:24},scene);post.position.set(x,.2,2.91);post.material=get('honey oak');shadow.addShadowCaster(post);}
 // Curtains are continuous flowing fabric, rather than cylinders.
 scene.meshes.filter(m=>m.name==='curtain fold').forEach(m=>m.dispose());
 for(const side of [-1,1]){const paths:Vector3[][]=[];for(let j=0;j<=28;j++){const row:Vector3[]=[];for(let i=0;i<=20;i++){const u=i/20,v=j/28;const spread=.53+.2*Math.sin(v*Math.PI);row.push(new Vector3(.2+side*(.99+u*spread+.1*Math.sin(v*Math.PI)),3.57-v*2.05,2.9+Math.sin(u*Math.PI*8)*(.06+v*.025)))}paths.push(row)}const curtain=MeshBuilder.CreateRibbon('linen curtain',{pathArray:paths,sideOrientation:Mesh.DOUBLESIDE},scene);curtain.material=get('cotton');curtain.receiveShadows=true;shadow.addShadowCaster(curtain);}
 // Soft contact shadows anchor furniture and the character to the ground.
 const ao=texture(scene,'contact shadow',128,(c,n)=>{const grad=c.createRadialGradient(n/2,n/2,2,n/2,n/2,n/2);grad.addColorStop(0,'#202d2780');grad.addColorStop(.4,'#202d2745');grad.addColorStop(1,'#202d2700');c.fillStyle=grad;c.fillRect(0,0,n,n)});ao.hasAlpha=true;
 const contactMat=material(scene,'contact shadow material','#ffffff');contactMat.diffuseTexture=ao;contactMat.opacityTexture=ao;contactMat.disableLighting=true;contactMat.emissiveColor=Color3.White();contactMat.useAlphaFromDiffuseTexture=true;contactMat.backFaceCulling=false;
 const contact=(x:number,z:number,w:number,d:number)=>{const p=MeshBuilder.CreateGround('soft contact shadow',{width:w,height:d},scene);p.position.set(x,.083,z);p.material=contactMat;p.isPickable=false;return p;};
 contact(-2.72,1.5,2.5,3.6);contact(.25,2.1,3,1.9);contact(2.85,2.65,2.5,1.5);contact(3.26,.69,1.1,1.1);const charShadow=contact(0,0,.8,.62);scene.onBeforeRenderObservable.add(()=>{charShadow.position.x=girl.position.x;charShadow.position.z=girl.position.z});
 // A richer stylized character: large eyes, sculpted fringe, pinafore and seams.
 get('skin').diffuseColor=Color3.FromHexString('#efc4a6');get('hair').diffuseColor=Color3.FromHexString('#4d332c');get('hair').specularColor=new Color3(.2,.13,.1);get('hair').specularPower=45;
 const childSphere=(name:string,x:number,y:number,z:number,sx:number,sy:number,sz:number,m:StandardMaterial)=>{const o=MeshBuilder.CreateSphere(name,{diameter:1,segments:24},scene);o.position.set(x,y,z);o.scaling.set(sx,sy,sz);o.parent=girl;o.material=m;shadow.addShadowCaster(o);return o;};
 scene.meshes.filter(m=>m.name==='eye').forEach(m=>m.dispose());
 const eyeWhite=material(scene,'eye whites','#fff8e8'),iris=material(scene,'hazel eyes','#605449'),apron=material(scene,'pinafore linen','#eadfc5');apron.diffuseTexture=fabric('apron weave','#eee1c5');apron.diffuseColor=Color3.White();
 for(const s of [-1,1]){childSphere('eye white',s*.098,1.398,.216,.091,.112,.035,eyeWhite);childSphere('iris',s*.098,1.39,.237,.059,.076,.016,iris);childSphere('pupil',s*.098,1.39,.246,.034,.052,.012,get('eyes'));childSphere('eye glint',s*.098-.012,1.413,.253,.017,.021,.008,eyeWhite);const brow=childSphere('eyebrow',s*.1,1.475,.211,.1,.024,.025,get('hair'));brow.rotation.z=s*.12;}
 for(let i=0;i<6;i++){const strand=childSphere('sculpted fringe',-.19+i*.073,1.57-Math.sin(i*.7)*.035,.151,.13,.21,.15,get('hair'));strand.rotation.z=-.2+i*.07;}
 childSphere('pinafore bib',0,.914,.159,.275,.25,.041,apron);
 for(const s of [-1,1]){const strap=childSphere('apron shoulder strap',s*.135,1.015,.102,.057,.15,.16,apron);strap.rotation.z=s*-.18;childSphere('apron button',s*.112,.967,.192,.03,.03,.015,get('brass'));childSphere('dress puff sleeve',s*.265,.93,.005,.22,.21,.25,get('dress'));}
 const skirt=scene.getMeshByName('dress skirt');skirt?.dispose();
 const dressPaths:Vector3[][]=[];for(let j=0;j<=20;j++){const row:Vector3[]=[];const v=j/20,r=.17+v*.15;for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;const rr=r+Math.cos(a*12)*.018*v;row.push(new Vector3(Math.cos(a)*rr,.86-v*.54+Math.cos(a*12)*.009*v,Math.sin(a)*rr))}dressPaths.push(row)}const skirtMesh=MeshBuilder.CreateRibbon('pleated dress',{pathArray:dressPaths,sideOrientation:Mesh.DOUBLESIDE},scene);skirtMesh.material=get('dress');skirtMesh.parent=girl;shadow.addShadowCaster(skirtMesh);
 const apronPaths:Vector3[][]=[];for(let j=0;j<=15;j++){const row:Vector3[]=[];const v=j/15;for(let i=0;i<=16;i++){const a=.74+i/16*1.66,r=.18+v*.142;row.push(new Vector3(Math.cos(a)*r,.81-v*.43,Math.sin(a)*r+.009))}apronPaths.push(row)}const apronMesh=MeshBuilder.CreateRibbon('curved pinafore',{pathArray:apronPaths,sideOrientation:Mesh.DOUBLESIDE},scene);apronMesh.material=apron;apronMesh.parent=girl;shadow.addShadowCaster(apronMesh);
 // Thin pointed leaves with a curved surface, veins and varied pigmentation.
 const leafTexture=texture(scene,'leaf veins',256,(c,n)=>{const grad=c.createLinearGradient(0,0,n,0);grad.addColorStop(0,'#416a45');grad.addColorStop(.5,'#87a26a');grad.addColorStop(1,'#527749');c.fillStyle=grad;c.fillRect(0,0,n,n);c.strokeStyle='#d6d59b66';c.lineWidth=2;c.beginPath();c.moveTo(n/2,0);c.lineTo(n/2,n);c.stroke();for(let y=20;y<n;y+=24){for(const s of [-1,1]){c.lineWidth=.8;c.beginPath();c.moveTo(n/2,y);c.quadraticCurveTo(n/2+s*40,y-12,n/2+s*110,y-45);c.stroke()}}});
 const leafMat=material(scene,'living foliage','#ffffff');leafMat.diffuseTexture=leafTexture;leafMat.backFaceCulling=false;leafMat.specularColor=new Color3(.15,.2,.1);
 for(const old of [...scene.meshes].filter(m=>m.name==='leaf')){const paths:Vector3[][]=[];for(let j=0;j<=16;j++){const row:Vector3[]=[];const v=j/16,span=Math.pow(Math.sin(v*Math.PI),.75)*.52;for(let i=0;i<=8;i++){const u=i/8*2-1;row.push(new Vector3(u*span,v-.5,Math.abs(u)*.1-Math.sin(v*Math.PI)*.21))}paths.push(row)}const leaf=MeshBuilder.CreateRibbon('veined curved leaf',{pathArray:paths,sideOrientation:Mesh.DOUBLESIDE},scene);leaf.position.copyFrom(old.position);leaf.rotation.copyFrom(old.rotation);leaf.scaling.set(old.scaling.x*1.5,old.scaling.y*1.35,old.scaling.y);leaf.material=leafMat;leaf.receiveShadows=true;shadow.addShadowCaster(leaf);old.dispose();}
 // Rounded ceramic pots and a glazed lip.
 for(const old of [...scene.meshes].filter(m=>m.name==='plant pot')){const bounds=old.getBoundingInfo().boundingBox.extendSize;const h=bounds.y*2,r=bounds.x;const pot=MeshBuilder.CreateLathe('handmade ceramic pot',{shape:[new Vector3(0,-h/2,0),new Vector3(r*.64,-h/2,0),new Vector3(r*.75,-h*.4,0),new Vector3(r*.95,h*.32,0),new Vector3(r,h*.43,0),new Vector3(r*.98,h*.51,0),new Vector3(r*.84,h*.51,0),new Vector3(r*.83,h*.37,0)],tessellation:48,sideOrientation:Mesh.DOUBLESIDE},scene);pot.position.copyFrom(old.position);pot.material=old.material;pot.receiveShadows=true;shadow.addShadowCaster(pot);old.dispose();}
 // A painted view through the window, with layered hills and little town roofs.
 const view=get('window sky');view.diffuseColor=Color3.White();view.emissiveColor=new Color3(.22,.23,.18);view.diffuseTexture=texture(scene,'garden outside',512,(c,n)=>{const sky=c.createLinearGradient(0,0,0,n);sky.addColorStop(0,'#b4d2d1');sky.addColorStop(.65,'#e3e6cb');sky.addColorStop(1,'#a8b38c');c.fillStyle=sky;c.fillRect(0,0,n,n);for(let layer=0;layer<3;layer++){c.fillStyle=['#9ab6a7','#839f86','#738e6d'][layer];c.beginPath();c.moveTo(0,n);for(let x=0;x<=n;x+=8)c.lineTo(x,260+layer*65+Math.sin(x*.012+layer)*40+Math.sin(x*.027)*13);c.lineTo(n,n);c.fill()}for(let i=0;i<4;i++){const x=90+i*94,y=310+i%2*22;c.fillStyle='#e4d8b9';c.fillRect(x,y,51,65);c.fillStyle='#ab806a';c.beginPath();c.moveTo(x-8,y);c.lineTo(x+25,y-35);c.lineTo(x+60,y);c.fill();c.fillStyle='#617f79';c.fillRect(x+12,y+19,11,17);c.fillRect(x+32,y+19,11,17)}});
 scene.meshes.filter(m=>m.name==='tree beyond window').forEach(m=>m.dispose());
 // A linen pennant garland and warm fairy lights on the left wall.
 const wirePoints:Vector3[]=[];for(let i=0;i<=40;i++){const t=i/40;wirePoints.push(new Vector3(-3.77,3.35-Math.sin(t*Math.PI)*.28,-2.6+t*4.7))}const wire=MeshBuilder.CreateTube('garland cord',{path:wirePoints,radius:.009,tessellation:6},scene);wire.material=get('walnut');
 const bulbMat=material(scene,'warm fairy lights','#ffe0a2');bulbMat.emissiveColor=Color3.FromHexString('#f9c46b');
 for(let i=0;i<11;i++){const t=(i+.5)/11,z=-2.6+t*4.7,y=3.35-Math.sin(t*Math.PI)*.28;const bulb=MeshBuilder.CreateSphere('tiny warm bulb',{diameter:.044,segments:10},scene);bulb.position.set(-3.74,y-.055,z);bulb.material=bulbMat;if(i%2===0){const flag=new Mesh('linen pennant',scene),data=new VertexData();data.positions=[-3.75,y-.08,z-.1,-3.75,y-.08,z+.1,-3.75,y-.36,z];data.indices=[0,1,2,2,1,0];data.normals=[1,0,0,1,0,0,1,0,0];data.uvs=[0,0,1,0,.5,1];data.applyToMesh(flag);flag.material=i%4===0?get('rose linen'):get('dress');}}
 // Improve the light response, contact depth and tonal range.
 for(const light of scene.lights){if(light instanceof HemisphericLight){light.intensity=.66;light.diffuse=Color3.FromHexString('#e5edf0');light.groundColor=Color3.FromHexString('#9c8e7e')}if(light instanceof DirectionalLight){light.intensity=1.15;light.diffuse=Color3.FromHexString('#ffead1')}}
 shadow.useBlurExponentialShadowMap=false;shadow.useContactHardeningShadow=true;shadow.contactHardeningLightSizeUVRatio=.06;shadow.filteringQuality=ShadowGenerator.QUALITY_MEDIUM;shadow.darkness=.2;shadow.normalBias=.025;
 scene.ambientColor=new Color3(.08,.08,.08);scene.clearColor=Color4.FromHexString('#e5e1d6ff');
 const pipeline=new DefaultRenderingPipeline('finish',true,scene,[camera]);pipeline.samples=4;pipeline.fxaaEnabled=true;pipeline.imageProcessingEnabled=true;pipeline.imageProcessing.contrast=1.12;pipeline.imageProcessing.exposure=1.02;pipeline.bloomEnabled=true;pipeline.bloomThreshold=1.05;pipeline.bloomWeight=.1;pipeline.bloomKernel=32;pipeline.bloomScale=.5;
 if(scene.getEngine().getCaps().drawBuffersExtension){const ssao=new SSAO2RenderingPipeline('contact depth',scene,{ssaoRatio:.6,blurRatio:1},[camera]);ssao.radius=.18;ssao.totalStrength=.4;ssao.expensiveBlur=false;ssao.samples=16;ssao.maxZ=40;}
}

