import './no-zoom';
import {createViewportSync} from './viewport';
import {ArcRotateCamera, Color3, Color4, DirectionalLight, Engine, HemisphericLight, MeshBuilder, Scene, ShadowGenerator, StandardMaterial, TransformNode, Vector3} from '@babylonjs/core';
import {loadLea,LeaClip} from './lea';
import './character.css';
document.querySelector('#app')!.innerHTML=`<canvas id="preview" aria-label="Трёхмерная модель Леи. Перетаскивайте для вращения, используйте колесо или щипок для приближения."></canvas><header><a href="/">← В комнату</a><span>ТИХИЙ ГОРОД / МАСТЕРСКАЯ</span></header><section class="intro"><small>ПЕРСОНАЖ 01</small><h1>Знакомьтесь, Лея.</h1><p>Новый образ для маленьких открытий.</p><div class="badge">Cute Chibi Girl</div></section><aside><span>АВТОР МОДЕЛИ</span><p><a href="https://sketchfab.com/3d-models/cute-chibi-girl-free-game-ready-character-28e2f98ab4bf4313a3f258d45d987716" target="_blank" rel="noopener noreferrer">Yury Misiyuk · Sketchfab</a><br>Лицензия CC BY 4.0</p></aside><nav aria-label="Анимации"><button data-clip="Idle" class="active">Стоит</button><button data-clip="Walk">Идёт</button><button data-clip="Interact">Исследует</button><button data-clip="Celebrate">Радуется</button><button id="face">Лицо крупно</button></nav><footer>Перетаскивай, чтобы повернуть · Приближай колесом или щипком</footer><div id="status" role="status">Загружаю модель…</div>`;
const canvas=document.querySelector<HTMLCanvasElement>('canvas')!;
const engine=new Engine(canvas,true,{stencil:true});engine.setHardwareScalingLevel(1/Math.min(devicePixelRatio,1.5));
const scene=new Scene(engine);scene.clearColor=Color4.FromHexString('#e9e4d9ff');
const camera=new ArcRotateCamera('portrait',-Math.PI/2-.20,1.36,2.9,new Vector3(0,.75,0),scene);camera.attachControl(canvas,true);camera.lowerRadiusLimit=.6;camera.upperRadiusLimit=4;camera.lowerBetaLimit=.4;camera.upperBetaLimit=1.65;camera.wheelPrecision=65;camera.pinchPrecision=100;camera.panningSensibility=0;camera.minZ=.02;
const fill=new HemisphericLight('fill',new Vector3(0,1,-.2),scene);fill.intensity=.65;fill.groundColor=Color3.FromHexString('#a59b86');
const key=new DirectionalLight('soft key',new Vector3(.5,-.9,.6),scene);key.position=new Vector3(-3,5,-4);key.intensity=2.2;key.diffuse=Color3.FromHexString('#ffe6c8');
const shadow=new ShadowGenerator(2048,key);shadow.usePercentageCloserFiltering=true;shadow.filteringQuality=ShadowGenerator.QUALITY_HIGH;shadow.bias=.001;shadow.normalBias=.008;shadow.darkness=.28;
const ground=MeshBuilder.CreateGround('studio floor',{width:200,height:200},scene);const groundMat=new StandardMaterial('ivory',scene);groundMat.diffuseColor=Color3.FromHexString('#e3ddce');groundMat.specularColor=Color3.Black();ground.material=groundMat;ground.receiveShadows=true;
const root=new TransformNode('Lea',scene);root.rotation.y=Math.PI;
let close=false;document.querySelector<HTMLButtonElement>('#face')!.onclick=()=>{close=!close;camera.target.set(0,close?1.22:.75,0);camera.radius=close?.92:2.9;document.querySelector('#face')!.textContent=close?'Во весь рост':'Лицо крупно'};
async function start(){try{const lea=await loadLea(scene,root,shadow);document.querySelector('#status')!.textContent='';document.querySelectorAll<HTMLButtonElement>('[data-clip]').forEach(b=>{b.disabled=false;b.onclick=()=>{lea.play(b.dataset.clip as LeaClip);document.querySelectorAll('[data-clip]').forEach(el=>el.classList.toggle('active',el===b))}})}catch(e){document.querySelector('#status')!.textContent='Не удалось загрузить модель. Обновите страницу.';console.error(e)}}
document.querySelectorAll<HTMLButtonElement>('[data-clip]').forEach(b=>b.disabled=true);void start();const viewport=createViewportSync(canvas,engine);engine.runRenderLoop(()=>{viewport.update();scene.render()});import.meta.hot?.dispose(()=>viewport.dispose());
