export type RoomId='bedroom'|'living'|'kitchen'|'bathroom'|'toilet'|'hall';
export type Obstacle={x:number;z:number;w:number;d:number};
export type Door={to:RoomId;x:number;z:number;wall:'back'|'left';approach:[number,number]};
export const roomNames:Record<RoomId,string>={bedroom:'Комната Леи',living:'Гостиная',kitchen:'Кухня',bathroom:'Ванная',toilet:'Туалет',hall:'Коридор'};
export const roomInfo:Record<RoomId,{description:string;story:string;width:number;depth:number;spawn:[number,number];doors:Door[];obstacles:Obstacle[]}>= {
 bedroom:{description:'У каждого открытия\nесть маленькое начало.',story:'Бабушкина шкатулка ждёт своего открытия.',width:8,depth:6.8,spawn:[1.5,-1.8],doors:[{to:'hall',x:-4,z:-.9,wall:'left',approach:[-3.1,-.9]}],obstacles:[{x:-2.72,z:1.43,w:1.9,d:3.2},{x:.22,z:2.12,w:2.5,d:1.3},{x:.25,z:1.13,w:.87,d:.86},{x:2.85,z:2.65,w:2.1,d:1.1},{x:3.26,z:.69,w:.9,d:.9},{x:-3.15,z:-2.27,w:1.1,d:1.1}]},
 living:{description:'Мягкий диван, любимые книги\nи время побыть вместе.',story:'Здесь семья собирается по вечерам. На столике уже ждёт настольная игра.',width:8,depth:6.8,spawn:[1.6,-1.8],doors:[{to:'hall',x:2.8,z:3.4,wall:'back',approach:[2.8,2.35]}],obstacles:[{x:-1.25,z:2.2,w:3.8,d:1.65},{x:-1,z:-.15,w:2,d:1.25},{x:-3.35,z:-1.4,w:.9,d:2.1},{x:2.55,z:-.9,w:1.4,d:1.5}]},
 kitchen:{description:'Солнечное утро начинается\nс запаха свежего хлеба.',story:'Кухня готова к завтраку. Можно осмотреть чайник и корзину с фруктами.',width:8,depth:6.8,spawn:[2.5,-1.8],doors:[{to:'hall',x:2.9,z:3.4,wall:'back',approach:[2.9,2.35]}],obstacles:[{x:-1.05,z:2.75,w:4.8,d:1.05},{x:-3.2,z:1.5,w:1.2,d:1.35},{x:-.15,z:-.5,w:2.7,d:2.2}]},
 bathroom:{description:'Тёплая вода, пушистые полотенца\nи маленький кораблик.',story:'Отдельная ванная комната. Нажми на кран, чтобы включить или выключить воду.',width:6.6,depth:6.8,spawn:[1.9,-1.7],doors:[{to:'hall',x:1.95,z:3.4,wall:'back',approach:[1.95,2.35]}],obstacles:[{x:-2,z:1.1,w:1.65,d:3.55},{x:-.05,z:2.85,w:1.65,d:.9},{x:2.3,z:.1,w:1,d:1.3}]},
 toilet:{description:'Небольшая отдельная комната\nс зелёной плиткой.',story:'Туалет отделён от ванной. Здесь есть умывальник, зеркало и полка для мелочей.',width:4.8,depth:5.6,spawn:[.7,-1.5],doors:[{to:'hall',x:1.25,z:2.8,wall:'back',approach:[1.25,1.8]}],obstacles:[{x:-1.35,z:1.4,w:1.1,d:1.55},{x:-1.85,z:-.7,w:.8,d:1.2}]},
 hall:{description:'Пять дверей —\nи целый дом открытий.',story:'Отсюда можно попасть во все комнаты. Нажми на название над дверью — Лея подойдёт и войдёт.',width:8,depth:6.8,spawn:[.2,-1.6],doors:[{to:'bedroom',x:-2.6,z:3.4,wall:'back',approach:[-2.6,2.35]},{to:'living',x:0,z:3.4,wall:'back',approach:[0,2.35]},{to:'kitchen',x:2.6,z:3.4,wall:'back',approach:[2.6,2.35]},{to:'bathroom',x:-4,z:.9,wall:'left',approach:[-3.1,.9]},{to:'toilet',x:-4,z:-1.5,wall:'left',approach:[-3.1,-1.5]}],obstacles:[{x:3,z:-.4,w:1.2,d:2.2}]}
};
export function isBlocked(id:RoomId,x:number,z:number){const r=roomInfo[id];return Math.abs(x)>r.width/2-.42||Math.abs(z)>r.depth/2-.37||r.obstacles.some(o=>Math.abs(x-o.x)<o.w/2+.14&&Math.abs(z-o.z)<o.d/2+.14)}
