import {freshQuest,restoreQuest,pour,award,unlock,medals,type Medal,type QuestState} from './memory-state';
import './memory.css';
export const medalNames:Record<Medal,string>={flower:'Цветок',cup:'Чашка',boat:'Кораблик',book:'Книга',moon:'Луна'};
const icons:Record<Medal,string>={flower:'❀',cup:'☕',boat:'⛵',book:'▤',moon:'☾'};
const clues:Record<Medal,string>={flower:'Цветы мы поливали раньше чая.',cup:'Чай был раньше, чем мы читали.',boat:'Кораблик мы запускали сразу после чая.',book:'Читали после корабликов, но ещё до того, как вышли смотреть на луну.',moon:'На обложке была луна. Вечером мы увидели такую же в небе.'};
const photoArt=`<rect width="300" height="180" fill="#dbcba9"/><rect x="18" y="15" width="80" height="100" rx="4" fill="#395666"/><circle cx="61" cy="42" r="19" fill="#f7e3a1"/><circle cx="69" cy="36" r="18" fill="#395666"/><path d="M58 15v100M18 70h80" stroke="#f5e5c6" stroke-width="5"/><path d="M116 93Q160 72 208 96V164H113Z" fill="#9ba58b"/><circle cx="159" cy="60" r="25" fill="#e8b694"/><path d="M132 60Q124 15 167 32Q193 33 181 66L171 40Z" fill="#dedcd1"/><path d="M130 92L161 103L188 90V131L160 145L130 128Z" fill="#586e64"/><path d="M150 113a12 12 0 1 0 10 18a10 10 0 0 1-10-18" fill="#f6dda0"/><path d="M215 143h75v10h-75zM226 153v27M277 153v27" fill="#947354"/><path d="M235 129h43l-10 12h-23Z" fill="#bc8568"/><path d="M253 103v25h18Z" fill="#fff3d7"/><path d="M235 148q8-5 17 0t19 0" fill="none" stroke="#64999c" stroke-width="3"/>`;
const crescent='M 62 12 A 39 39 0 1 0 62 88 A 42 42 0 0 1 62 12 Z';
const $=(s:string)=>document.querySelector<HTMLElement>(s)!;
export function createMemoryQuest(ui:{modal:(html:string)=>void;close:()=>void;celebrate:()=>void;exit:()=>void;changed:()=>void},storageKey='logictown-memory-v1'){
 let state:QuestState=freshQuest();try{state=restoreQuest(JSON.parse(localStorage.getItem(storageKey)||'null'))}catch{}
 const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(state))}catch{}ui.changed()};
 const button=(id:string,text:string,cls='secondary')=>`<button class="${cls}" id="${id}">${text}</button>`;
 const feedback=(text:string)=>{$('#memory-feedback').textContent=text};
 function frame(title:string,body:string){ui.modal(`<div class="memory"><h2 id="modal-title">${title}</h2>${body}<p id="memory-feedback" role="status" aria-live="polite"></p></div>`)}
 const bind=(id:string,fn:()=>void)=>{$('#'+id).onclick=fn};
 function reward(m:Medal){save();ui.celebrate();frame('Найден медальон',`<div class="medal-big">${icons[m]}</div><h3>${medalNames[m]}</h3><p>На обороте:</p><blockquote>${clues[m]}</blockquote>${button('memory-done','Забрать и продолжить','primary')}`);bind('memory-done',ui.close)}
 function earned(m:Medal){if(state.earned.includes(m)){reward(m);return true}return false}
 function intro(){frame('Дом помнит',`<p>«Лея, ключ от входной двери лежит в шкафчике в коридоре. Пять деревянных медальонов помогут вспомнить наш день: от утра до вечера».</p><p>Исследуй весы на кухне, кораблик в ванной, зеркало, фотоальбом и театр теней. Три части фотографии лежат в спальне, на кухне и в ванной.</p><blockquote>«Теперь у тебя будет своя история.<br>Бабушка»</blockquote>${button('memory-done','Начать исследовать','primary')}`);bind('memory-done',ui.close)}
 function kitchen(){if(earned('cup'))return;const tilt=(state.plums-5)*3;
 frame('Весы на кухне',`<p>Яблоко = груша + слива<br>Груша = две сливы</p><svg class="puzzle-art" viewBox="0 0 300 150" role="img" aria-label="Весы: слева яблоко и груша, справа ${state.plums} слив"><path d="M150 45v92M118 137h64" stroke="#856445" stroke-width="8"/><g transform="rotate(${tilt} 150 45)"><path d="M47 45h206M65 45v49M235 45v49" stroke="#856445" stroke-width="5"/><path d="M26 94q39 43 78 0M196 94q39 43 78 0" fill="#c4aa6c"/><text x="36" y="90" font-size="29">🍎🍐</text><text x="207" y="90" font-size="25">${state.plums} ●</text></g></svg><p>Сколько слив уравновесят яблоко и грушу?</p><div class="memory-controls">${button('plum-minus','− Слива')}<output aria-label="Число слив">${state.plums}</output>${button('plum-plus','+ Слива')}</div>${button('weigh','Проверить равновесие','primary')}`);
 bind('plum-minus',()=>{state.plums=Math.max(0,state.plums-1);save();kitchen()});bind('plum-plus',()=>{state.plums=Math.min(9,state.plums+1);save();kitchen()});bind('weigh',()=>award(state,'cup')?reward('cup'):feedback('Весы наклонены. Подумай, сколько слив заменяют каждый фрукт.'));}
 function bathroom(){if(earned('boat'))return;
 const vessel=(n:number,i:number)=>`<div class="vessel"><svg viewBox="0 0 100 150" role="img" aria-label="Кувшин ${[3,5][i]}: ${n} из ${[3,5][i]}"><path d="M15 20v115h70V20" fill="#eee6d6" stroke="#809a96" stroke-width="4"/><rect x="18" y="${133-n/[3,5][i]*108}" width="64" height="${n/[3,5][i]*108}" fill="#7cbec3"/>${Array.from({length:[3,5][i]},(_,j)=>`<path d="M70 ${133-(j+1)/[3,5][i]*108}h12" stroke="#4c7272"/>`).join('')}${i===1?`<text x="28" y="${129-n/5*108}" font-size="20">⛵</text>`:''}</svg><strong>${n} / ${[3,5][i]}</strong>${button('fill'+i,'Наполнить '+[3,5][i])}${button('empty'+i,'Опорожнить '+[3,5][i])}</div>`;
 frame('Кораблик и вода',`<p>Дверца плавучего домика откроется на уровне <strong>4</strong> в большом кувшине. Есть только кувшины на 3 и 5.</p><div class="vessels">${state.jugs.map(vessel).join('')}</div><div class="memory-controls">${button('pour0','3 → 5')}${button('pour1','5 → 3')}</div>${button('water-check','Открыть домик','primary')}`);
 for(const i of [0,1] as const){bind('fill'+i,()=>{state.jugs[i]=[3,5][i];save();bathroom()});bind('empty'+i,()=>{state.jugs[i]=0;save();bathroom()});bind('pour'+i,()=>{state.jugs=pour(state.jugs,i);save();bathroom()})}bind('water-check',()=>award(state,'boat')?reward('boat'):feedback('Нужен уровень ровно 4 в большом кувшине. Переливай до края или пока маленький кувшин не опустеет.'));}
 let reflected=false;const glyphs=['❀','◒','✦'];
 function toilet(){if(earned('flower'))return;
 frame('Узор в зеркале',`<p>На стене — странный узор. У коробочки три поворотных диска.</p><div class="mirror-pair"><div><small>Узор на стене</small><div class="mirror-code reversed" aria-label="Зеркально написанный узор">✦ ❀ ◒</div></div><div class="mirror-glass"><small>Зеркало</small><div class="mirror-code" ${reflected?'':'aria-hidden="true"'}>${reflected?'✦ ❀ ◒':'◇'}</div></div></div>${button('look-mirror',reflected?'Отвернуть зеркало':'Повернуть зеркало к узору')}<div class="memory-controls">${state.mirror.map((v,i)=>button('dial'+i,`${i+1} · ${glyphs[v]}`)).join('')}</div>${button('mirror-check','Открыть коробочку','primary')}`);
 bind('look-mirror',()=>{reflected=!reflected;toilet()});for(let i=0;i<3;i++)bind('dial'+i,()=>{state.mirror[i]=(state.mirror[i]+1)%3;save();toilet()});bind('mirror-check',()=>award(state,'flower')?reward('flower'):feedback('Замок не открылся. Посмотри на порядок рисунков именно в отражении.'));}
 function fragment(i:number){if(!state.fragments.includes(i)){state.fragments.push(i);save()}frame('Фрагмент фотографии',`<svg class="photo-found" viewBox="${i*100} 0 100 180" role="img" aria-label="Часть семейной фотографии">${photoArt}</svg><p>Найдено частей: ${state.fragments.length} из 3. Альбом лежит на столике в гостиной.</p>${button('memory-done','Положить в альбом','primary')}`);bind('memory-done',ui.close)}
 let selected=-1;
 function living(){if(earned('book'))return;
 frame('Семейный альбом',`<p>${state.fragments.length<3?'Фотография разорвана. Найди три части: в спальне, на кухне и в ванной.':'Выбери две части фотографии, чтобы поменять их местами.'}</p><div class="photo-pieces">${state.photo.map((piece,i)=>`<button id="piece${i}" class="photo-piece ${selected===i?'chosen':''}" aria-label="Фрагмент в позиции ${i+1}" ${state.fragments.includes(piece)?'':'disabled'}>${state.fragments.includes(piece)?`<svg viewBox="${piece*100} 0 100 180">${photoArt}</svg>`:'?'}</button>`).join('')}</div><p>${state.fragments.length}/3 фрагмента</p>${button('photo-check','Восстановить фотографию','primary')}`);
 for(let i=0;i<3;i++)bind('piece'+i,()=>{if(selected<0)selected=i;else{[state.photo[selected],state.photo[i]]=[state.photo[i],state.photo[selected]];selected=-1;save()}living()});bind('photo-check',()=>{if(award(state,'book')){save();ui.celebrate();frame('Воспоминание восстановлено',`<svg class="puzzle-art" viewBox="0 0 300 180" role="img" aria-label="Бабушка читает книгу с полумесяцем, рядом мокрый кораблик, за окном луна">${photoArt}</svg><blockquote>${clues.book}</blockquote><p>На обложке книги — силуэт для театра теней в комнате Леи.</p>${button('memory-done','Забрать медальон книги','primary')}`);bind('memory-done',ui.close)}else feedback('Края рисунка пока не совпадают или найдены не все части.');});}
 function bedroom(){if(earned('moon'))return;
 const shadows=state.shadows.map((angle,i)=>`<g transform="rotate(${angle*90} 50 50)"><path d="${crescent}" clip-path="url(#band${i})" fill="#374c4b"/></g>`).join('');
 frame('Театр теней',`<p>Поворачивай три фигурки. Их тени должны сложиться в силуэт с обложки книги на семейной фотографии.</p><div class="shadow-stage"><svg viewBox="0 0 100 100" role="img" aria-label="Три поворотные тени"><defs>${[0,1,2].map(i=>`<clipPath id="band${i}"><rect x="0" y="${i*34}" width="100" height="34"/></clipPath>`).join('')}</defs><circle cx="50" cy="50" r="48" fill="#f6e3ac"/>${shadows}</svg>${state.earned.includes('book')?`<svg class="shadow-target" viewBox="0 0 100 100" role="img" aria-label="Образец с фотографии: полумесяц"><path d="${crescent}" fill="#526b60"/></svg>`:'<span>Образец ещё не найден</span>'}</div><div class="memory-controls">${state.shadows.map((_,i)=>button('shadow'+i,'Фигурка '+(i+1)+' ↻')).join('')}</div>${button('shadow-check','Проверить силуэт','primary')}`);
 for(let i=0;i<3;i++)bind('shadow'+i,()=>{state.shadows[i]=(state.shadows[i]+1)%4;save();bedroom()});bind('shadow-check',()=>award(state,'moon')?reward('moon'):feedback(state.earned.includes('book')?'Тени ещё не образуют нужный силуэт.':'Сначала восстанови фотографию в гостиной, чтобы узнать нужный силуэт.'));}
 function cabinet(){if(state.key){frame('Ключ найден',`<div class="medal-big">⚿</div><blockquote>«Теперь у тебя есть своя история. Пора узнать, что за порогом».</blockquote><p>Ключ сохранён. Входная дверь — в правом конце коридора.</p>${button('memory-done','К двери','primary')}`);bind('memory-done',ui.close);return}
 frame('Дом помнит',`<p>«Вспомни, как прошёл наш день. Начни с утра, закончи вечером».</p><div class="memory-order">${Array.from({length:5},(_,i)=>`<button class="secondary" id="slot${i}" aria-label="Гнездо ${i+1}: ${state.order[i]?medalNames[state.order[i]]:'пусто'}">${state.order[i]?icons[state.order[i]]:'·'}</button>`).join('')}</div><p>Нажми на медальон, чтобы поставить его в следующее гнездо. Нажми на гнездо, чтобы вернуть медальон.</p><div class="medal-tray">${(['moon','cup','book','flower','boat'] as Medal[]).map(m=>`<button id="medal-${m}" class="secondary" ${!state.earned.includes(m)||state.order.includes(m)?'disabled':''}>${icons[m]} ${medalNames[m]}</button>`).join('')}</div><details><summary>Записки на медальонах · ${state.earned.length}/5</summary>${state.earned.map(m=>`<blockquote><strong>${icons[m]} ${medalNames[m]}</strong><br>${clues[m]}</blockquote>`).join('')||'<p>Медальоны спрятаны в пяти комнатах. Ищи значки над предметами.</p>'}</details><div class="memory-controls">${button('quest-note','Записка бабушки')}${button('cabinet-check','Открыть шкафчик','primary')}</div>`);
 medals.forEach(m=>bind('medal-'+m,()=>{if(state.earned.includes(m)&&!state.order.includes(m)){state.order.push(m);save();cabinet()}}));for(let i=0;i<5;i++)bind('slot'+i,()=>{state.order.splice(i,1);save();cabinet()});bind('quest-note',intro);bind('cabinet-check',()=>{if(unlock(state)){save();ui.celebrate();cabinet()}else feedback(state.earned.length<5?'Не хватает медальонов. Исследуй остальные комнаты.':'Все медальоны на месте, но история пока не складывается. Сверь порядок с записками.');});}
 function door(){if(!state.key){frame('Входная дверь заперта',`<p>На замке — пять знакомых рисунков. Ключ лежит в шкафчике в коридоре.</p>${button('memory-done','Продолжить поиски','primary')}`);bind('memory-done',ui.close);return}frame('За порогом',`<div class="medal-big">⚿</div><p>Ключ подошёл. За дверью солнечный день.</p>${button('leave-house','Открыть дверь и выйти','primary')}`);bind('leave-house',()=>{state.exited=true;save();ui.close();ui.exit()})}
 return {state,intro,kitchen,bathroom,toilet,living,bedroom,fragment,cabinet,door};
}
