// Generated by scripts/prepare-colonial-houses.mjs from actual mesh bounds.
export const outdoorHouseProfiles={"a":{"w":15.2,"h":9.15,"d":13.02},"b":{"w":13.6,"h":9.2,"d":12.62},"c":{"w":14.4,"h":9.13,"d":12.82},"d":{"w":13.4,"h":7.73,"d":12.9}};
